### ISSUE TITLE
请求地址被转义

### ISSUE THREAD

**Issue by gpkchen** [IANIx/SwiftMoya#1]
`   public var baseURL: URL {
//        let defaultBase = URL(string: NetworkManager.manager.serverType.baseUrl())!
        return URL(string: "http:192.168.1.130:22222/transfer-storage-platform-app-server")!
    }`

当我使用这个地址的时候，接口变成了http:192.168.1.130%2a22222
看不出是哪里操作

**Comment by IANIx** [comment]
let defaultBase =  URL(string: "http://192.168.1.130:22222/transfer-storage-platform-app-server")!

**Comment by gpkchen** [comment]
it works！感谢！
